config/routes.rb
FortuneResponders::Application.routes.draw do

  resources :fortunes do
    resources :comments
    collection do
      get :tags
    end
  end

  root :to => 'fortunes#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :fortune
  attr_accessible :author, :body

  validates :author, presence: true
  validates :body, presence: true

end

app/models/fortune.rb
# -*- coding: utf-8 -*-

class Fortune < ActiveRecord::Base
  has_many :comments, :dependent => :destroy

  attr_accessible :quotation, :source

  validates :quotation, presence: true
  validates :quotation, length: { maximum: 256 }
  validates :quotation, uniqueness: { case_sensitive: false }

  validates :source, length: { in: 3..64 }, allow_blank: true

  acts_as_taggable_on :tags
  ActsAsTaggableOn::TagList.delimiter = " "

  # def self.text_search(query)
  #   if query.present?
  #     # SQLite i PostgreSQL
  #     where('quotation like :q or source like :q', q: "%#{query}%").order('created_at DESC')
  #     # tylko PostgreSQL, i – ignore case
  #     # where("quotation ilike :q or source ilike :q", q: "%#{query}%").order('created_at DESC')
  #   else
  #     scoped
  #   end
  # end

  # def self.text_search(query)
  #   if query.present?
  #     where("quotation @@ :q or source @@ :q", q: query).order('created_at DESC')
  #   else
  #     scoped
  #   end
  # end

  # def self.text_search(query)
  #   if query.present?
  #     # where("quotation @@ :q or source @@ :q", q: query)
  #     orquery = <<-ORQUERY
  #     to_tsvector('english', quotation) @@ plainto_tsquery('english', #{sanitize(query)})
  #       or
  #     to_tsvector('english', source) @@ plainto_tsquery('english', #{sanitize(query)})
  #   ORQUERY
  #     where(orquery)
  #   else
  #     scoped
  #   end
  # end


  # Texticle

  # def self.text_search(query)
  #   if query.present?
  #     search(query)    # metoda zdefiniowana w Texticle
  #   else
  #     scoped
  #   end
  # end


  # PgSearch, default: rank DESC

  include PgSearch

  # definiujemy metodę `search`
  pg_search_scope :fortunes_search,
      against: [:quotation, :source],
      using: {tsearch: {dictionary: "english"}}

  def self.text_search(query)
    if query.present?
      fortunes_search(query)    # metoda zdefiniowana powyżej
    else
      scoped
    end
  end

end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html, :atom
  respond_to :json, except: [:create, :update, :destroy]

  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter do
    @fortune = Fortune.find(params[:fortune_id])
  end

  # POST /fortunes/:fortune_id/comments
  def create
    @comment = @fortune.comments.build(params[:comment])
    @comment.save
    respond_with(@fortune, @comment, location: @fortune)
  end

  # DELETE /fortunes/:fortune_id/comments/:id
  def destroy
    @comment = @fortune.comments.find(params[:id])
    @comment.destroy
    respond_with(@fortune, @comment, location: @fortune)
  end

  # GET /fortunes/:fortune_id/comments/:id/edit
  def edit
    @comment = @fortune.comments.find(params[:id])
  end

  # PUT /fortunes/:fortune_id/comments/:id
  def update
    @comment = @fortune.comments.find(params[:id])
    @comment.update_attributes(params[:comment])
    respond_with(@fortune, @comment, location: @fortune)
  end

end

app/controllers/fortunes_controller.rb
class FortunesController < ApplicationController
  before_filter only: [:index, :tags] do
    @tags = Fortune.tag_counts
  end

  def tags
    @fortunes = Fortune.tagged_with(params[:name])
      .page(params[:page]).per_page(4)
    respond_with(@fortunes) do |format|
      format.html { render action: 'index' }
    end
  end

  # GET /fortunes
  def index
    # @fortunes = Fortune.all
    @fortunes = Fortune.text_search(params[:query])
      .page(params[:page]).per_page(4)

    respond_with(@fortunes)
  end

  # GET /fortunes/1
  def show
    @fortune = Fortune.find(params[:id])
    @comment = Comment.new
    respond_with(@fortune)
  end

  # GET /fortunes/new
  def new
    @fortune = Fortune.new
    respond_with(@fortune)
  end

  # GET /fortunes/1/edit
  def edit
    @fortune = Fortune.find(params[:id])
  end

  # POST /fortunes
  def create
    @fortune = Fortune.new(params[:fortune])
    @fortune.save
    respond_with(@fortune)
  end

  # PUT /fortunes/1
  def update
    @fortune = Fortune.find(params[:id])
    @fortune.update_attributes(params[:fortune])
    respond_with(@fortune)
  end

  # DELETE /fortunes/1
  def destroy
    @fortune = Fortune.find(params[:id])
    @fortune.destroy
    respond_with(@fortune)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/fortunes_helper.rb
module FortunesHelper
end

app/helpers/layout_helper.rb
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
#
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end
  def show_title?
    @show_title
  end
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/comments/_comment.html.erb
<div class="attribute">
  <span class="name"><%= t "simple_form.labels.comment.body" %></span>
  <span class="value"><%= comment.body %></span>
</div>
<div class="attribute">
  <span class="name"><%= t "simple_form.labels.comment.author" %></span>
  <span class="value"><%= comment.author %></span>
</div>

<div class="form-actions">
  <%= link_to 'Edit', edit_fortune_comment_path(@fortune, comment), class: 'btn-mini' %>
  <%= link_to 'Destroy', [@fortune, comment], method: :delete, class: 'btn-mini btn-danger'%>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for [@fortune, @comment], :html => { :class => 'form-horizontal' } do |f| %>
<% if f.error_notification %>
<div class="alert alert-error fade in">
  <a class="close" data-dismiss="alert" href="#">&times;</a>
  <%= f.error_notification %>
</div>
<% end %>
<div class="form-inputs">
  <%= f.input :author %>
  <%= f.input :body %>
</div>
<div class="form-actions">
  <%= f.button :submit %>
</div>
<% end %>

app/views/comments/edit.html.erb
<% title "Editing comment" %>

<%= render :partial => 'form' %>

<div class="form-actions">
  <%= link_to 'Show Fortune', @comment.fortune, class: 'btn' %>
</div>

app/views/comments/new.html.erb
<% title "New comment" %>

<%= render partial: 'form' %>

<div class="form-actions">
  <%= link_to 'Back to Fortune', @comment.fortune, class: 'btn' %>
</div>

app/views/common/_flashes.html.erb
<% flash.each do |name, msg| %>
<div class="alert alert-<%= name == :notice ? "success" : "error" %>">
  <a class="close" data-dismiss="alert">×</a>
  <%= msg %>
</div>
<% end %>

app/views/common/_footer.html.erb
<p><small>&copy; Powered by Rails 3.2 &amp; Bootstrap 2.0, from Twitter</small>

app/views/common/_menu.html.erb
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</a>
<a class="brand" href="#">Responders</a>
<div class="nav-collapse">
  <ul class="nav">
    <li><%= link_to "Home", '#' %>
    <li><%= link_to "About", '#' %>
    <li><%= link_to "Contact", '#' %>
  </ul>
</div>

app/views/fortunes/_form.html.erb
<%= simple_form_for(@fortune) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :quotation, :input_html => { :rows => 6 } %>
    <%= f.input :source %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/fortunes/_fortune.html.erb
<article class="index">
  <div class="attribute">
    <span class="name"><%= t "simple_form.labels.fortune.quotation" %></span>
    <span class="value"><%= fortune.quotation %></span>
  </div>
  <div class="attribute">
    <span class="name"><%= t "simple_form.labels.fortune.source" %></span>
    <span class="value"><%= fortune.source %></span>
  </div>
  <div class="attribute">
    <span class="name"><%= t "simple_form.labels.fortune.tags" %></span>
    <span class="value tags"><%= fortune.tag_list.join(", ") %>
    </span>
  </div>

  <div class="form-actions">
    <%= link_to 'Show', fortune, class: 'btn btn-mini'%>
    <%= link_to 'Edit', edit_fortune_path(fortune), class: 'btn btn-mini'%>
    <%= link_to 'Destroy', fortune, confirm: 'Are you sure?', method: :delete, class: 'btn btn-mini btn-danger'%>
  </div>
</article>

app/views/fortunes/edit.html.erb
<% title "Editing fortune" %>

<%= render partial: 'form'%>

app/views/fortunes/index.html.erb
<% title "All fortunes" %>

<div id="tag-cloud">
  <% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
  <%= link_to tag.name, tags_fortunes_path(name: tag.name), class: css_class %>
  <% end %>
</div>

<%= form_tag fortunes_path, method: :get, id: "fortunes_search", class: "form-inline" do %>
  <%= text_field_tag :query, params[:query] %>
  <%= submit_tag "Search", name: nil, class: "btn" %>
<% end %>

<div class="digg_pagination">
  <div class="page_info">
    <%= page_entries_info @fortunes %>
  </div>
  <%= will_paginate @fortunes, :container => false %>
</div>

<%= render partial: 'fortune', collection: @fortunes %>

<div class="form-actions">
  <%= link_to 'New Fortune', new_fortune_path, class: 'btn btn-primary'%>
</div>

app/views/fortunes/new.html.erb
<% title "New fortune" %>

<%= render partial: 'form'%>

app/views/fortunes/show.html.erb
<% title "Show fortune" %>

<article class="show">
  <div class="attribute">
    <span class="name"><%= t "simple_form.labels.fortune.quotation" %></span>
    <span class="value"><%= @fortune.quotation %></span>
  </div>
  <div class="attribute">
    <span class="name"><%= t "simple_form.labels.fortune.source" %></span>
    <span class="value"><%= @fortune.source %></span>
  </div>

  <div class="form-actions">
    <%= link_to 'Back', fortunes_path, class: 'btn'%>
    <%= link_to 'Edit', edit_fortune_path(@fortune), class: 'btn' %>
    <%= link_to 'Destroy', @fortune, confirm: 'Are you sure?', method: :delete, class: 'btn btn-danger'%>
  </div>

  <h2>Add new comment</h2>
  <%= render partial: 'comments/form' %>

  <% if @fortune.comments.any? %>
  <h2>Comments</h2>
  <%= render partial: 'comments/comment', collection: @fortune.comments %>
  <% end %>

</article>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="pl">
  <head>
    <meta charset="utf-8">
    <title><%= content_for?(:title) ? yield(:title) : "Responders" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <%= auto_discovery_link_tag(:atom, fortunes_path(:atom)) %>

    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

    <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <%= render :partial => 'common/menu' %>
        </div>
      </div>
    </div>

    <div class="container">
      <%= render :partial => 'common/flashes' %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
      <footer>
        <%= render :partial => 'common/footer' %>
      </footer>
    </div>

  </body>
</html>